title: "Ruby or Rails"
summary: "Ruby か Rails のメモ"
topics:
  - "rails"
  - "ruby"
published: false
price: 0
toc_depth: 3
allow_override: true
chapters:
  - "07de07"
  - "ae8cf2"
  - "aeddef"
  - "fff243"
  - "94070b"
